#!/bin/sh
#
# Raspberry Pi Garage door controller service
# $Id: ggpiod,v 1.2 2014/06/18 16:57:10 bob Exp $
#
# Author : Bob Rathbone
# Site   : http://www.bobrathbone.com
#
# This script controls the ggpiod service
#
# License: GNU V3, See https://www.gnu.org/copyleft/gpl.html
#
# Disclaimer: Software is provided as is and absolutly no warranties are implied or given.
#             The authors shall not be liable for any loss or damage however caused.
#
### BEGIN INIT INFO
# Provides:          ggpiod
# Should-Start:      
# Should-Stop:       
# Required-Start:    $remote_fs $syslog   
# Required-Stop:     $remote_fs $syslog 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Raspberry PI Radio Daemon
# Description:       Start the Radio Daemon (ggpiod) service
#                    for network access to the local audio queue.
### END INIT INFO

. /lib/lsb/init-functions

PATH=/sbin:/bin:/usr/sbin:/usr/bin

# Change NAME parameter this next line to the version of the daemon you are using
# Choices are ggpiod.py, radio4.py, rggpiod.py, rradio4.py or ada_radio.py
# No spaces around the = character
NAME=ggpiod.py
CGI_BIN=/var/www/cgi-bin
DAEMON=${CGI_BIN}/${NAME}

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

case "$1" in
    start)
        ${DAEMON} start
        ;;
    stop)
        ${DAEMON} stop
        ;;
    status)
        ${DAEMON} status
	;;
    relay)
        ${DAEMON} relay
	;;
    open)
        ${DAEMON} open
	;;
    close)
        ${DAEMON} close
	;;
    version)
        ${DAEMON} version
	;;
    restart)
        ${DAEMON} restart
        ;;
    force-reload)
        ${DAEMON} restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status|open|close|relay}"
        exit 2
        ;;
esac
